version:  3.8
services:
  postgres:
    image: postgres:15-alpine
    container_name: collab-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: collab
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  yjs:
    image: node:18-alpine
    container_name: collab-yjs
    working_dir: /app
    command: ["node", "server.js"]
    ports:
      - "1234:1234"
    volumes:
      - ./apps/yjs:/app
      - yjsdata:/app/yjs-data

  coturn:
    image: instrumentisto/coturn
    container_name: collab-coturn
    network_mode: host # for local; in prod, expose ports 3478/5349 and set external-ip
    environment:
      - REALM=collab.local
    command: >
      -n --log-file=stdout
      -a -f -r collab.local
      --min-port=49160 --max-port=49200
      --lt-cred-mech
      --user turnuser:turnpass
      --no-tls --no-dtls

volumes:
  pgdata:
  yjsdata:
