services:
  # Backend API Server
  - type: web
    name: remote-collab-backend
    runtime: node
    plan: starter
    buildCommand: pnpm install && cd apps/api && pnpm prisma generate && pnpm build
    startCommand: cd apps/api && pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: remote-collab-db
          property: connectionString
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: REDIS_URL
        sync: false
        optional: true

databases:
  - name: remote-collab-db
    plan: starter
    databaseName: remote_collab
    databaseUser: remote_collab_user

